name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use your project's Node.js version

    - name: Install dependencies
      run: npm install  # Replace with 'yarn install' if using Yarn

    - name: Run tests
      run: npm test  # Assumes you have a 'test' script in your package.json. Remove if not applicable.

  deploy:
    needs: build  # Makes sure the build job completes before this runs
    runs-on: ubuntu-latest

    steps:
    - name: Install Vercel CLI
      run: npm i -g vercel

    - name: Deploy to Vercel
      run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod

